print("venta de producto")
print("ingresa nombre del producto")
nomprod=input("televisor")
print("ingresa precio unitario del producto")
puprod=input(1250)
puprod=int(1250)
print("ingresa cantidad del producto")
cantprod=input(5)
cantprod=int(5)
print("ingrese resultado de la multiplicacion")
imp=input(1250*5)
print("ingrese resultado")
dsct=input(6250*0.05)
print("ingrese total")
total=input(6250-312.5)

